package game;

import java.awt.Color;

/**
 * One narrative chapter in Classic mode. A chapter spans a few levels and
 * sets the visual accent color (HUD tint, level-up flash) plus the wave
 * pacing for those levels.
 *
 * Levels not covered by an explicit chapter fall back to an "endless path"
 * chapter generated by {@link #getForLevel(int)}.
 */
public final class Chapter {

    public final int id;
    public final String name;
    public final String tagline;
    public final int[] levels;
    public final Color accent;
    public final int[] wavesPerLevel;
    public final int[] fruitsPerWave;
    public final int[] fruitsPerWaveMax;
    public final long wavePauseMs;

    public Chapter(int id, String name, String tagline, int[] levels,
                   Color accent, int[] wavesPerLevel, int[] fruitsPerWave,
                   int[] fruitsPerWaveMax, long wavePauseMs) {
        this.id = id;
        this.name = name;
        this.tagline = tagline;
        this.levels = levels;
        this.accent = accent;
        this.wavesPerLevel = wavesPerLevel;
        this.fruitsPerWave = fruitsPerWave;
        this.fruitsPerWaveMax = fruitsPerWaveMax;
        this.wavePauseMs = wavePauseMs;
    }

    public int indexOfLevel(int level) {
        for (int i = 0; i < levels.length; i++) {
            if (levels[i] == level) return i;
        }
        return Math.max(0, levels.length - 1);
    }

    public static final Chapter[] CHAPTERS = {
        new Chapter(1, "The Dojo", "Begin your training",
                    new int[] { 1, 2 },
                    new Color(196, 154, 108),
                    new int[] { 3, 4 },
                    new int[] { 3, 4 },
                    new int[] { 5, 6 },
                    1200),
        new Chapter(2, "Bamboo Grove", "The blade grows sharper",
                    new int[] { 3, 4, 5 },
                    new Color(109, 186, 94),
                    new int[] { 4, 5, 5 },
                    new int[] { 4, 5, 5 },
                    new int[] { 6, 7, 8 },
                    1100),
        new Chapter(3, "The Marketplace", "Faster hands, richer bounty",
                    new int[] { 6, 7 },
                    new Color(232, 166, 66),
                    new int[] { 5, 6 },
                    new int[] { 5, 6 },
                    new int[] { 8, 9 },
                    1000),
        new Chapter(4, "Shadow Temple", "Darkness tests the worthy",
                    new int[] { 8, 9, 10 },
                    new Color(138, 94, 207),
                    new int[] { 6, 6, 7 },
                    new int[] { 6, 6, 7 },
                    new int[] { 9, 10, 10 },
                    900),
        new Chapter(5, "Dragon's Peak", "Only legends survive",
                    new int[] { 11, 12, 13 },
                    new Color(231, 76, 60),
                    new int[] { 7, 7, 8 },
                    new int[] { 7, 7, 8 },
                    new int[] { 10, 11, 12 },
                    800),
    };

    public static Chapter getForLevel(int level) {
        for (Chapter c : CHAPTERS) {
            for (int l : c.levels) {
                if (l == level) return c;
            }
        }
        // Endless fallback
        int extra = Math.max(0, level - 13);
        int waves = Math.min(10, 7 + extra / 2);
        int minFruits = Math.min(10, 7 + extra / 3);
        int maxFruits = Math.min(15, 10 + extra / 2);
        long pause = Math.max(600, 800 - extra * 20);
        return new Chapter(6 + extra / 3, "The Endless Path",
                           "No master ever rests", new int[] { level },
                           new Color(231, 76, 60),
                           new int[] { waves },
                           new int[] { minFruits },
                           new int[] { maxFruits },
                           pause);
    }

    public static boolean isNewChapterStart(int level) {
        for (Chapter c : CHAPTERS) {
            if (c.levels.length > 0 && c.levels[0] == level) return true;
        }
        return false;
    }

    public static String toRoman(int n) {
        int[] vals  = { 10, 9, 5, 4, 1 };
        String[] syms = { "X", "IX", "V", "IV", "I" };
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < vals.length; i++) {
            while (n >= vals[i]) { out.append(syms[i]); n -= vals[i]; }
        }
        return out.toString();
    }
}
